---
nextcloud_enabled: false
nextcloud_available_externally: "false"

# directories
nextcloud_directory: "{{ docker_home }}/nextcloud"
nextcloud_data_directory: "{{ samba_shares_root }}/nextcloud"

# network
nextcloud_port: "8082"
nextcloud_hostname: "nextcloud"

# username / passwords
nextcloud_sql_user: "nextcloud-user"
nextcloud_sql_password: "nextcloud-pass"
nextcloud_sql_root_password: "nextcloud-secret"

# specs
nextcloud_memory: 2g
nextcloud_mysql_memory: 2g
