---
 - name: Create qBittorrent Directories
   file:
     path: "{{ item }}"
     state: directory
     # mode: 0755
   with_items:
     - "{{ qbittorrent_data_directory }}"
     - "{{ qbittorrent_data_directory }}/config"
     - "{{ qbittorrent_download_directory }}"
     - "{{ qbittorrent_watch_directory }}"

 - name: qBittorrent
   docker_container:
     name: qbittorrent
     image: linuxserver/qbittorrent
     pull: true
     volumes:
       - "{{ qbittorrent_config_directory }}:/config:rw"
       - "{{ qbittorrent_download_directory }}:/downloads_incomplete:rw"
       - "{{ qbittorrent_completed_download_directory }}:/downloads:rw"
     ports:
       - "{{ qbittorrent_webui_port }}:8080"
       - "{{ qbittorrent_bt_port }}:6881"
       - "{{ qbittorrent_bt_port }}:6881/udp"
     env:
       TZ: "{{ ansible_nas_timezone }}"
       PUID: "{{ qbittorrent_user_id }}"
       PGID: "{{ qbittorrent_group_id }}"
     restart_policy: unless-stopped
     memory: "{{ qbittorrent_memory }}"
     labels:
       traefik.enable: "{{ qbittorrent_available_externally }}"
       traefik.http.routers.qbittorrent.rule: "Host(`{{ qbittorrent_hostname }}.{{ ansible_nas_domain }}`)"
       traefik.http.routers.qbittorrent.tls.certresolver: "letsencrypt"
       traefik.http.routers.qbittorrent.tls.domains[0].main: "{{ ansible_nas_domain }}"
       traefik.http.routers.qbittorrent.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
       traefik.http.services.qbittorrent.loadbalancer.server.port: "8080"