---
- name: MiniDLNA Docker Container
  docker_container:
    name: minidlna
    image: vladgh/minidlna
    pull: true
    volumes:
      - "{{ minidlna_media_directory1 }}:/movies:rw"
      - "{{ minidlna_media_directory2 }}:/tv:rw"
    env:
      MINIDLNA_MEDIA_DIR1: "/movies"
      MINIDLNA_MEDIA_DIR2: "/tv"
      MINIDLNA_FRIENDLY_NAME: "{{ minidlna_friendly_name }}"
      MINIDLNA_PORT: "{{ minidlna_port }}"
    restart_policy: unless-stopped
    network_mode: host
    memory: "{{ minidlna_memory }}"
